# .pre-commit-config.yaml
repos:
  # Standard file checks (whitespace, valid yaml, etc.)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Ruff: The modern, fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

    # Spelling
  - repo: https://github.com/crate-ci/typos
    rev: dictgen-v0.3.1
    hooks:
      - id: typos
        exclude: |
          (?x)(
            ^hmnd_playground|
            BUILD$|
            \.(cc|cpp|cxx|c|h|hpp|hxx|lsl|ld|py|s|S)$
          )
  # XML
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        language_version: 20.11.1
        additional_dependencies:
          - "prettier@3.1.0"
          - "@prettier/plugin-xml@3.3.1"
        files: \.(xml|xacro|srdf|urdf)$
  # Markdown
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: ["--fix", "--config", ".markdownlint.yaml"]
  # Github Actions
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  # C++
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        files: \.(cpp|cxx|c|h|hpp|hxx|txx)$
  # CMake
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        additional_dependencies: [pyyaml>=5.1]
      - id: cmake-lint
        additional_dependencies: [pyyaml>=5.1]
        args:
          - "--disabled-codes=C0301" # Disable Line too long lint
  # Jupyter Notebooks - Clear outputs
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        files: \.ipynb$
        # language_version: python3.11
