[workspace]
authors = ["anubhav-dogra <anubhavdograa@gmail.com>"]
channels = ["conda-forge"]
name = "robot_rl"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mujoco = ">=3.3.7,<4"
gymnasium-mujoco = ">=1.2.2,<2"
pytorch = ">=2.9.1,<3"
matplotlib = ">=3.10.8,<4"
pyright = ">=1.1.407,<2"

[feature.lint.dependencies]
pre-commit = "*"

[feature.lint.tasks]
lint = "pre-commit run --all-files"

[environments]
lint = { features = ["lint"], no-default-feature = true }
